export const SAVE_CONSULTATION_SUCCESS = 'SAVE_CONSULTATION_SUCCESS';
export const SAVE_CONSULTATION_FAILED = 'SAVE_CONSULTATION_FAILED';
export const SAVE_CONSULTATION = 'SAVE_CONSULTATION';
export const CLOSE_SNACK_BAR = 'CLOSE_SNACK_BAR';
